In [1]:
import tensorflow as tf

In [3]:
m=tf.constant([[1,2,3,4],[2,8,1,5],[45,78,2,7],[23,67,2,4]])
print(m)

tf.Tensor(
[[ 1  2  3  4]
 [ 2  8  1  5]
 [45 78  2  7]
 [23 67  2  4]], shape=(4, 4), dtype=int32)


In [4]:
mmax=tf.reduce_max(m,axis=1)
print (mmax)

tf.Tensor([ 4  8 78 67], shape=(4,), dtype=int32)


In [5]:
v1=tf.constant([[2,5,1],[7,12,4],[2,5,6]])
v2=tf.constant([[2,5,1],[7,4,2],[1,2,2]])
v3=v1+v2
print(v3)

tf.Tensor(
[[ 4 10  2]
 [14 16  6]
 [ 3  7  8]], shape=(3, 3), dtype=int32)


In [11]:
list=[[1,2,1],[2,2,1],[5,6,1]]
v5=v3+list
print(v5)

tf.Tensor(
[[ 5 12  3]
 [16 18  7]
 [ 8 13  9]], shape=(3, 3), dtype=int32)
